### ISSUE TITLE
[Update Your User Profile] Allow a close button to remove an 'Add a financial institutions` window

### ISSUE THREAD

**Issue by shindigira** [cfpb/sbl-frontend#197] opened 2024-01-29 19:47 UTC
Post-MVP:

Should allow a 'close button' to be able to remove non-associated and non-pending institutions (from previous submissions).

The use case is for when a user may inadvertently click 'Add a financial institutions` too many times.

**Comment by billhimmelsbach** [comment] 2024-09-10 18:36
Consolidated it all in one ticket. A duplicate of #596

**Closed by billhimmelsbach** 2024-09-10 18:36 UTC
Labels: enhancement, UI, post-mvp
