### ISSUE TITLE
[Task] Lint existing code

### ISSUE THREAD

**Issue by meissadia** [cfpb/sbl-frontend#84] opened 2023-12-13 21:46 UTC
Now that we have Husky running pre-commit checks, one of which is ESLint to identify and address unwanted code patterns, we should run through the existing code and address issues that have already made their way into the code.

My thoughts on how this would go:
- Run `yarn run-eslint` to auto fix anything that can be
- Work through the errors that require manual intervention (currently ~120 errors in ~25 files)
- Merge all that effort into `main`
- Avoid any new issues getting merged thanks to pre-commit checks

**Comment by meissadia** [comment] 2024-01-18 19:32
Bill has already run linting but I want to verify that this is completed before closing.

**Comment by billhimmelsbach** [comment] 2024-09-10 16:59
Keeping this one around, and going to prioritize it next sprint.

**Comment by billhimmelsbach** [comment] 2024-09-10 17:48
Duplicate of #717 (includes TS errors)

**Closed as not planned by billhimmelsbach** 2024-09-10 17:48 UTC
Labels: triage
